const authErrorKeys = {
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  CREDENTIALS_REQUIRED: "CREDENTIALS_REQUIRED",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  UNAUTHORIZED_ACCESS: "UNAUTHORIZED_ACCESS",
  FORBIDDEN_ACCESS: "FORBIDDEN_ACCESS",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  INVALID_USERNAME_OR_PASSWORD: "INVALID_USERNAME_OR_PASSWORD",
};

export default authErrorKeys;
