const authErrorKeys = {
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  CREDENTIALS_REQUIRED: "CREDENTIALS_REQUIRED",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  UNAUTHORIZED_ACCESS: "UNAUTHORIZED_ACCESS",
  FORBIDDEN_ACCESS: "FORBIDDEN_ACCESS",
};

export default authErrorKeys;
