const subscriptionErrorKeys = {
  SUBSCRIPTION_NOT_FOUND: "SUBSCRIPTION_NOT_FOUND",
  SUBSCRIPTION_CREATION_FAILED: "SUBSCRIPTION_CREATION_FAILED",
  SUBSCRIPTION_UPDATE_FAILED: "SUBSCRIPTION_UPDATE_FAILED",
  SUBSCRIPTION_DELETION_FAILED: "SUBSCRIPTION_DELETION_FAILED",
  INVALID_SUBSCRIPTION_DATA: "INVALID_SUBSCRIPTION_DATA",
  SUBSCRIPTION_FETCH_FAILED: "SUBSCRIPTION_FETCH_FAILED",
};

export default subscriptionErrorKeys;
